"""Graphviz DOT exporter with one cluster per group and layer-colored nodes."""

from __future__ import annotations

from pattern_detector.adapters.outbound.formatters.graph_grouping import (
    cycle_edge_pairs,
    grouped_nodes,
)
from pattern_detector.domain.architecture.models import (
    ArchitectureScanResult,
    ArchLayer,
)
from pattern_detector.ports.outbound.arch_exporter_port import (
    ArchitectureExporterPort,
    GraphViewOptions,
)

_LAYER_FILL: dict[ArchLayer, str] = {
    ArchLayer.DOMAIN: "#d3f1e0",  # green — the innermost layer
    ArchLayer.PORTS: "#e4d9f2",  # purple
    ArchLayer.ADAPTERS: "#d9e8f7",  # blue
    ArchLayer.INFRASTRUCTURE: "#f7e6c9",  # amber
    ArchLayer.API: "#f7d0d0",  # red-ish
    ArchLayer.SHARED: "#e8e8e8",  # grey
    ArchLayer.UNKNOWN: "#ffffff",
}

_KIND_LABEL = {
    "open": "open",
    "include": "include",
    "functor_application": "functor",
    "qualified_reference": "ref",
}


def _escape(text: str) -> str:
    """Escape a string for a DOT quoted identifier."""
    return text.replace("\\", "\\\\").replace('"', '\\"')


class DotArchitectureFormatter(ArchitectureExporterPort):
    """Renders the component graph as a Graphviz DOT digraph with clusters."""

    extension = "dot"

    def format(self, result: ArchitectureScanResult, options: GraphViewOptions | None = None) -> str:
        options = options or GraphViewOptions()
        lines: list[str] = [
            f'// generated by dpx arch — {result.project_path}',
            'digraph architecture {',
            '  rankdir=LR;',
            '  graph [fontname="Helvetica", label="Module dependency graph", labelloc=t, fontsize=18];',
            '  node [shape=box, style="rounded,filled", fontname="Helvetica", fontsize=11];',
            '  edge [fontname="Helvetica", fontsize=9, color="#7a869a"];',
        ]

        visible = {n.id for _, nodes in grouped_nodes(result, options.group_by, options.show_cycles_only) for n in nodes}

        for i, (group_label, nodes) in enumerate(grouped_nodes(result, options.group_by, options.show_cycles_only)):
            lines.append(f'  subgraph cluster_{i} {{')
            lines.append(f'    label="{_escape(group_label)}";')
            lines.append('    style="rounded,filled"; color="#dfe5ec"; fillcolor="#f6f8fa";')
            for node in nodes:
                fill = _LAYER_FILL[node.layer]
                border = '#e05252' if node.cycle_id is not None else '#9aa5b1'
                attrs = [f'label="{_escape(node.name)}"', f'fillcolor="{fill}"', f'color="{border}"']
                if node.is_entry:
                    attrs.append('penwidth=2')
                lines.append(f'    "{_escape(node.id)}" [{", ".join(attrs)}];')
            lines.append("  }")

        cycle_pairs = cycle_edge_pairs(result)
        for edge in result.graph.edges:
            if edge.source not in visible or edge.target not in visible:
                continue
            attrs = [f'label="{_KIND_LABEL.get(edge.kind.value, edge.kind.value)}"', f'weight={max(1, edge.weight)}']
            if (edge.source, edge.target) in cycle_pairs:
                attrs.extend(['color="#d63c3c"', 'penwidth=2', 'fontcolor="#d63c3c"'])
            elif edge.cross_library:
                attrs.extend(['color="#b0650f"', 'style=dashed'])
            lines.append(f'  "{_escape(edge.source)}" -> "{_escape(edge.target)}" [{", ".join(attrs)}];')

        lines.append("}")
        return "\n".join(lines) + "\n"
