"""Mermaid flowchart exporter with one subgraph per group (library / layer / directory)."""

from __future__ import annotations

import re

from pattern_detector.adapters.outbound.formatters.graph_grouping import (
    cycle_edge_pairs,
    grouped_nodes,
)
from pattern_detector.domain.architecture.models import ArchitectureScanResult
from pattern_detector.ports.outbound.arch_exporter_port import (
    ArchitectureExporterPort,
    GraphViewOptions,
)

_KIND_LABEL = {
    "open": "open",
    "include": "include",
    "functor_application": "functor",
    "qualified_reference": "ref",
}

_UNSAFE_ID_RE = re.compile(r"[^A-Za-z0-9_]")


def safe_id(node_id: str) -> str:
    """Mermaid-safe node identifier (dots and other symbols become underscores)."""
    sid = _UNSAFE_ID_RE.sub("_", node_id)
    return f"n{sid}" if sid[:1].isdigit() else sid


class MermaidArchitectureFormatter(ArchitectureExporterPort):
    """Renders the component graph as a Mermaid ``graph TD`` definition."""

    extension = "mmd"

    def format(self, result: ArchitectureScanResult, options: GraphViewOptions | None = None) -> str:
        options = options or GraphViewOptions()
        lines: list[str] = [f"%% generated by dpx arch — {result.project_path}", "graph TD"]

        visible = {n.id for _, nodes in grouped_nodes(result, options.group_by, options.show_cycles_only) for n in nodes}
        in_cycle = {n.id for n in result.graph.nodes.values() if n.cycle_id is not None}

        for group_label, nodes in grouped_nodes(result, options.group_by, options.show_cycles_only):
            group_id = safe_id(f"group_{group_label}")
            lines.append(f'  subgraph {group_id}["{group_label}"]')
            for node in nodes:
                badge = " 🔁" if node.id in in_cycle else ""
                iface = " 📄" if node.has_interface else ""
                entry = " 🚪" if node.is_entry else ""
                lines.append(f'    {safe_id(node.id)}["{node.name}{iface}{entry}{badge}"]')
            lines.append("  end")

        cycle_pairs = cycle_edge_pairs(result)
        for edge in result.graph.edges:
            if edge.source not in visible or edge.target not in visible:
                continue
            label = _KIND_LABEL.get(edge.kind.value, edge.kind.value)
            style = "==>" if edge.weight >= 5 else "-->"
            if (edge.source, edge.target) in cycle_pairs:
                lines.append(f'  {safe_id(edge.source)} == "{label} ×{edge.weight}" ==> {safe_id(edge.target)}')
            elif edge.cross_layer and not edge.cross_library:
                lines.append(f'  {safe_id(edge.source)} -. "{label}" .-> {safe_id(edge.target)}')
            else:
                text = f"{label} · cross-lib" if edge.cross_library else label
                lines.append(f'  {safe_id(edge.source)} {style}|"{text}"| {safe_id(edge.target)}')

        for node_id in sorted(in_cycle & visible):
            lines.append(f"  style {safe_id(node_id)} stroke:#e05252,stroke-width:2px")
        if in_cycle & visible:
            lines.append("  classDef cycle stroke:#e05252,stroke-width:2px,color:#b23030")

        return "\n".join(lines) + "\n"
