"""Mermaid flowchart exporter with one subgraph per group (library / layer / directory)."""

from __future__ import annotations

import re

from pattern_detector.adapters.outbound.formatters.graph_grouping import (
    cycle_edge_pairs,
    grouped_nodes,
)
from pattern_detector.domain.architecture.models import ArchitectureScanResult
from pattern_detector.ports.outbound.arch_exporter_port import (
    ArchitectureExporterPort,
    GraphViewOptions,
)

_KIND_LABEL = {
    "open": "open",
    "include": "include",
    "functor_application": "functor",
    "qualified_reference": "ref",
}

_UNSAFE_ID_RE = re.compile(r"[^A-Za-z0-9_]")


def safe_id(node_id: str) -> str:
    """Mermaid-safe node identifier (dots and other symbols become underscores)."""
    sid = _UNSAFE_ID_RE.sub("_", node_id)
    return f"n{sid}" if sid[:1].isdigit() else sid


MAX_MERMAID_EDGES = 480


class MermaidArchitectureFormatter(ArchitectureExporterPort):
    """Renders the component graph as a Mermaid ``graph TD`` definition."""

    extension = "mmd"

    def format(self, result: ArchitectureScanResult, options: GraphViewOptions | None = None) -> str:
        options = options or GraphViewOptions()
        lines: list[str] = [f"%% generated by dpx arch — {result.project_path}", "graph TD"]

        visible = {n.id for _, nodes in grouped_nodes(result, options.group_by, options.show_cycles_only) for n in nodes}
        in_cycle = {n.id for n in result.graph.nodes.values() if n.cycle_id is not None}
        cycle_pairs = cycle_edge_pairs(result)

        candidate_edges = [
            e for e in result.graph.edges
            if e.source in visible and e.target in visible
        ]

        # GitHub enforces a strict 500-edge limit on Mermaid diagrams.
        # If total edges exceed MAX_MERMAID_EDGES, prioritize architectural components.
        if len(candidate_edges) > MAX_MERMAID_EDGES:
            def is_test_node(nid: str) -> bool:
                node = result.graph.nodes.get(nid)
                if not node:
                    return False
                fp = node.file_path.replace("\\", "/")
                return (
                    "/test/" in fp
                    or fp.startswith("test/")
                    or node.name.startswith("Test_")
                    or node.name == "Run_tests"
                )

            prod_edges = [
                e for e in candidate_edges
                if not is_test_node(e.source) and not is_test_node(e.target)
            ]
            if len(prod_edges) <= MAX_MERMAID_EDGES:
                candidate_edges = prod_edges
                visible = {nid for nid in visible if not is_test_node(nid)}
                lines.insert(1, "%% Note: Test modules omitted to comply with GitHub 500-edge limit.")
            else:
                def edge_score(e) -> tuple[int, int, int, int]:
                    in_c = 0 if (e.source, e.target) in cycle_pairs else 1
                    cross_lib = 0 if e.cross_library else 1
                    cross_lay = 0 if e.cross_layer else 1
                    return (in_c, cross_lib, cross_lay, -e.weight)

                prod_edges.sort(key=edge_score)
                candidate_edges = prod_edges[:MAX_MERMAID_EDGES]
                active_nodes = {e.source for e in candidate_edges} | {e.target for e in candidate_edges} | in_cycle
                visible = {nid for nid in visible if not is_test_node(nid)} & active_nodes
                lines.insert(1, "%% Note: Edges prioritized and capped to comply with GitHub 500-edge limit.")

        for group_label, nodes in grouped_nodes(result, options.group_by, options.show_cycles_only):
            group_nodes = [n for n in nodes if n.id in visible]
            if not group_nodes:
                continue
            group_id = safe_id(f"group_{group_label}")
            lines.append(f'  subgraph {group_id}["{group_label}"]')
            for node in group_nodes:
                badge = " 🔁" if node.id in in_cycle else ""
                iface = " 📄" if node.has_interface else ""
                entry = " 🚪" if node.is_entry else ""
                lines.append(f'    {safe_id(node.id)}["{node.name}{iface}{entry}{badge}"]')
            lines.append("  end")

        for edge in candidate_edges:
            label = _KIND_LABEL.get(edge.kind.value, edge.kind.value)
            style = "==>" if edge.weight >= 5 else "-->"
            if (edge.source, edge.target) in cycle_pairs:
                lines.append(f'  {safe_id(edge.source)} == "{label} ×{edge.weight}" ==> {safe_id(edge.target)}')
            elif edge.cross_layer and not edge.cross_library:
                lines.append(f'  {safe_id(edge.source)} -. "{label}" .-> {safe_id(edge.target)}')
            else:
                text = f"{label} · cross-lib" if edge.cross_library else label
                lines.append(f'  {safe_id(edge.source)} {style}|"{text}"| {safe_id(edge.target)}')

        for node_id in sorted(in_cycle & visible):
            lines.append(f"  style {safe_id(node_id)} stroke:#e05252,stroke-width:2px")
        if in_cycle & visible:
            lines.append("  classDef cycle stroke:#e05252,stroke-width:2px,color:#b23030")

        return "\n".join(lines) + "\n"
